server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;

    location /terms-of-service {
        try_files $uri $uri/ /terms-of-service/index.html;
    }

    location /privacy-policy {
        try_files $uri $uri/ /privacy-policy/index.html;
    }

    location / {
        return 301 https://savina.vn;
    }
}
