server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;

    location = /tiktok5aDdCZHbSvYJQ6rmPN3rMMj9SPNxzG5T.txt {
        try_files $uri =404;
    }

    location /terms-of-service {
        try_files $uri $uri/ /terms-of-service/index.html;
    }

    location /privacy-policy {
        try_files $uri $uri/ /privacy-policy/index.html;
    }

    location / {
        try_files $uri =404;
    }
}
